services:
  frontend:
    image: boses/study-reminder-front:latest
    ports:
      - '80:80'
    environment:
      # 配置后端服务地址，nginx模板会自动替换
      - BACKEND_URL=http://backend:3001
      - SOCKET_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: boses/study-reminder-backend:latest
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-study_user}:${POSTGRES_PASSWORD:-yoursecurepassword}@postgres_db:5432/${POSTGRES_DB:-study_reminder_db}?schema=public
      # 邮件相关
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SECURE=${MAIL_SECURE}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - JWT_SECRET=${JWT_SECRET}

    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    command: >
      sh -c "npx prisma migrate deploy && node dist/src/main"

  postgres_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-study_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-yoursecurepassword}
      POSTGRES_DB: ${POSTGRES_DB:-study_reminder_db}
      TZ: Asia/Shanghai
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - study_reminder_pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-study_user} -d ${POSTGRES_DB:-study_reminder_db} -q',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  app-network:
    driver: bridge

volumes:
  study_reminder_pgdata: {}
