/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogOnImport } from './routes/log-on'
import { Route as CoreImport } from './routes/_core'
import { Route as IndexImport } from './routes/index'
import { Route as CoreSetUpImport } from './routes/_core/set-up'
import { Route as CoreDashboardImport } from './routes/_core/dashboard'
import { Route as CoreAddCourseImport } from './routes/_core/add-course'
import { Route as CoreAboutImport } from './routes/_core/about'
import { Route as CoreManageCoursesIndexImport } from './routes/_core/manage-courses/index'

// Create/Update Routes

const LogOnRoute = LogOnImport.update({
  id: '/log-on',
  path: '/log-on',
  getParentRoute: () => rootRoute,
} as any)

const CoreRoute = CoreImport.update({
  id: '/_core',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CoreSetUpRoute = CoreSetUpImport.update({
  id: '/set-up',
  path: '/set-up',
  getParentRoute: () => CoreRoute,
} as any)

const CoreDashboardRoute = CoreDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CoreRoute,
} as any)

const CoreAddCourseRoute = CoreAddCourseImport.update({
  id: '/add-course',
  path: '/add-course',
  getParentRoute: () => CoreRoute,
} as any)

const CoreAboutRoute = CoreAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => CoreRoute,
} as any)

const CoreManageCoursesIndexRoute = CoreManageCoursesIndexImport.update({
  id: '/manage-courses/',
  path: '/manage-courses/',
  getParentRoute: () => CoreRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_core': {
      id: '/_core'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CoreImport
      parentRoute: typeof rootRoute
    }
    '/log-on': {
      id: '/log-on'
      path: '/log-on'
      fullPath: '/log-on'
      preLoaderRoute: typeof LogOnImport
      parentRoute: typeof rootRoute
    }
    '/_core/about': {
      id: '/_core/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof CoreAboutImport
      parentRoute: typeof CoreImport
    }
    '/_core/add-course': {
      id: '/_core/add-course'
      path: '/add-course'
      fullPath: '/add-course'
      preLoaderRoute: typeof CoreAddCourseImport
      parentRoute: typeof CoreImport
    }
    '/_core/dashboard': {
      id: '/_core/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof CoreDashboardImport
      parentRoute: typeof CoreImport
    }
    '/_core/set-up': {
      id: '/_core/set-up'
      path: '/set-up'
      fullPath: '/set-up'
      preLoaderRoute: typeof CoreSetUpImport
      parentRoute: typeof CoreImport
    }
    '/_core/manage-courses/': {
      id: '/_core/manage-courses/'
      path: '/manage-courses'
      fullPath: '/manage-courses'
      preLoaderRoute: typeof CoreManageCoursesIndexImport
      parentRoute: typeof CoreImport
    }
  }
}

// Create and export the route tree

interface CoreRouteChildren {
  CoreAboutRoute: typeof CoreAboutRoute
  CoreAddCourseRoute: typeof CoreAddCourseRoute
  CoreDashboardRoute: typeof CoreDashboardRoute
  CoreSetUpRoute: typeof CoreSetUpRoute
  CoreManageCoursesIndexRoute: typeof CoreManageCoursesIndexRoute
}

const CoreRouteChildren: CoreRouteChildren = {
  CoreAboutRoute: CoreAboutRoute,
  CoreAddCourseRoute: CoreAddCourseRoute,
  CoreDashboardRoute: CoreDashboardRoute,
  CoreSetUpRoute: CoreSetUpRoute,
  CoreManageCoursesIndexRoute: CoreManageCoursesIndexRoute,
}

const CoreRouteWithChildren = CoreRoute._addFileChildren(CoreRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof CoreRouteWithChildren
  '/log-on': typeof LogOnRoute
  '/about': typeof CoreAboutRoute
  '/add-course': typeof CoreAddCourseRoute
  '/dashboard': typeof CoreDashboardRoute
  '/set-up': typeof CoreSetUpRoute
  '/manage-courses': typeof CoreManageCoursesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof CoreRouteWithChildren
  '/log-on': typeof LogOnRoute
  '/about': typeof CoreAboutRoute
  '/add-course': typeof CoreAddCourseRoute
  '/dashboard': typeof CoreDashboardRoute
  '/set-up': typeof CoreSetUpRoute
  '/manage-courses': typeof CoreManageCoursesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_core': typeof CoreRouteWithChildren
  '/log-on': typeof LogOnRoute
  '/_core/about': typeof CoreAboutRoute
  '/_core/add-course': typeof CoreAddCourseRoute
  '/_core/dashboard': typeof CoreDashboardRoute
  '/_core/set-up': typeof CoreSetUpRoute
  '/_core/manage-courses/': typeof CoreManageCoursesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/log-on'
    | '/about'
    | '/add-course'
    | '/dashboard'
    | '/set-up'
    | '/manage-courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/log-on'
    | '/about'
    | '/add-course'
    | '/dashboard'
    | '/set-up'
    | '/manage-courses'
  id:
    | '__root__'
    | '/'
    | '/_core'
    | '/log-on'
    | '/_core/about'
    | '/_core/add-course'
    | '/_core/dashboard'
    | '/_core/set-up'
    | '/_core/manage-courses/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoreRoute: typeof CoreRouteWithChildren
  LogOnRoute: typeof LogOnRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoreRoute: CoreRouteWithChildren,
  LogOnRoute: LogOnRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_core",
        "/log-on"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_core": {
      "filePath": "_core.tsx",
      "children": [
        "/_core/about",
        "/_core/add-course",
        "/_core/dashboard",
        "/_core/set-up",
        "/_core/manage-courses/"
      ]
    },
    "/log-on": {
      "filePath": "log-on.tsx"
    },
    "/_core/about": {
      "filePath": "_core/about.tsx",
      "parent": "/_core"
    },
    "/_core/add-course": {
      "filePath": "_core/add-course.tsx",
      "parent": "/_core"
    },
    "/_core/dashboard": {
      "filePath": "_core/dashboard.tsx",
      "parent": "/_core"
    },
    "/_core/set-up": {
      "filePath": "_core/set-up.tsx",
      "parent": "/_core"
    },
    "/_core/manage-courses/": {
      "filePath": "_core/manage-courses/index.tsx",
      "parent": "/_core"
    }
  }
}
ROUTE_MANIFEST_END */
